import pkg from './hashMap.js'
const { HashMap } = pkg

const test = new HashMap() // or HashMap() if using a factory

test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')
test.set('mango', 'orange')
test.set('nectarine', 'red')
test.set('onion', 'white')
test.set('peach', 'pink')
test.set('quilt', 'multicolor')
test.set('rabbit', 'gray')
test.set('strawberry', 'red')
test.set('tomato', 'red')
test.set('umbrella', 'blue')
test.set('vanilla', 'cream')
test.set('watermelon', 'green')
test.set('app', 'colorful')
test.set('app', 'football')
test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')
test.set('mango', 'orange')
test.set('nectarine', 'red')
test.set('onion', 'white')
test.set('peach', 'pink')
test.set('quilt', 'multicolor')
test.set('rabbit', 'gray')
test.set('strawberry', 'red')
test.set('tomato', 'red')
test.set('umbrella', 'blue')
test.set('vanilla', 'cream')
test.set('watermelon', 'green')
test.set('app', 'colorful')
test.set('app', 'football')
test.show()
console.log(test.length())
console.log(test.get('alberto'))
console.log(test.has('vanilla'))
console.log(test.remove('vanilla'))
test.show()

console.log(test.keys())
console.log(test.values())
console.log(test.entries())

// node main.mjs